### ISSUE TITLE
Install arrayfire-rb on macos

### ISSUE THREAD

**Issue by ruggieroguida** [prasunanand/arrayfire-rb#1]
I am struggling to install arrayfire-rb on macos

Arrayfire was installed from here

[](http://arrayfire.com/download/)

I am installing the ruby bindings from here

[](https://github.com/prasunanand/arrayfire-rb)

Everything works up to 

`bundle install`

but when I launch

`rake install`

I receive several 

```
In file included from ../../../../ext/mri/ruby_arrayfire.cpp:5:
/usr/local/include/af/cuda.h:12:10: error: 'cuda.h' file not found with <angled> include; use "quotes"
      instead
#include <cuda.h>
         ^~~~~~~~
         "cuda.h"
```

Any advice?

**Comment by prasunanand** [comment]
Moved to https://github.com/arrayfire/arrayfire-rb/issues/6

@Rojj I am working on it
